"use client"

import { motion } from "framer-motion"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Building, Calendar, MapPin, Briefcase } from "lucide-react"

const professionalExperience = [
  { id: 1, title: "Frontend Developer", company: "Triotech Systems", location: "Toronto, Ontario", period: "October 2024 – May 2025", type: "Full-time", description: ["Shipped production UI features for a multi-tenant SaaS platform using React.js, TypeScript, and Tailwind CSS.", "Integrated REST APIs with the Node.js backend team, closing data-flow gaps to keep frontend state and backend responses in sync.", "Worked inside Git, Docker, and CI/CD pipelines for full-lifecycle delivery — from local development to production deployment.", "Diagnosed and resolved production issues by tracing behavior from the browser through API responses to backend logs."], technologies: ["React.js", "TypeScript", "Tailwind CSS", "Docker", "CI/CD"] },
  { id: 2, title: "Junior Frontend Developer Intern", company: "Triotech Systems", location: "Toronto, Ontario", period: "January 2024 – October 2024", type: "Internship", description: ["Built UI components using React.js and TypeScript, and integrated REST APIs into existing SaaS modules.", "Debugged and improved components across student and class management modules — reading existing architecture and reverse-engineering intended behavior.", "Worked inside Git-based version control and Agile ceremonies (daily standups, sprint planning) as part of a live engineering team."], technologies: ["React.js", "TypeScript", "REST APIs", "Git"] },
]

const universityExperience = [
  { id: 3, title: "Peer Learning Mentor", company: "Algoma University", location: "Brampton, Ontario", period: "July 2026 – Present", type: "Campus Leadership", description: ["Provide structured 1-on-1 mentorship and recurring student check-ins", "Log CCR milestones and connect students with relevant campus resources", "Act as a direct escalation link for academic and personal support needs"], technologies: ["Mentorship", "Student Support", "Case Management"], current: true },
  { id: 4, title: "Student Life Ambassador", company: "Algoma University", location: "Brampton, Ontario", period: "February 2026 – June 2026", type: "Campus Operations", description: ["Serve as a frontline resolution point for incoming students", "Support onboarding and help students navigate institutional systems", "Coordinate with campus departments to resolve questions and incidents"], technologies: ["Onboarding", "Incident Resolution", "Coordination"] },
  { id: 5, title: "Orientation Leader", company: "Algoma University", location: "Brampton, Ontario", period: "September 2025 – January 2026", type: "Campus Leadership", description: ["Managed check-in workflows for new student orientation", "Guided students through digital registration portals", "Coordinated event logistics and cross-team communication"], technologies: ["Workflow Design", "Registration Systems", "Logistics"] },
]

function ExperienceGroup({ title, intro, items }: { title: string; intro: string; items: typeof professionalExperience }) {
  return <div className="mb-14 last:mb-0"><div className="mb-7 max-w-2xl"><h3 className="text-2xl font-semibold text-foreground">{title}</h3><p className="text-muted-foreground mt-2 leading-relaxed">{intro}</p></div><div className="relative"><div className="absolute left-8 md:left-1/2 top-0 bottom-0 w-px bg-accent/40 md:-translate-x-1/2" /><div className="space-y-8">{items.map((exp, index) => <motion.div key={exp.id} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: .5, delay: index * .06 }} viewport={{ once: true }} className={`relative flex flex-col md:flex-row items-center gap-8 ${index % 2 ? "md:flex-row-reverse" : ""}`}><div className="absolute left-[25px] md:left-1/2 w-2 h-2 rounded-full bg-accent ring-4 ring-background md:-translate-x-1/2" /><div className="w-full md:w-5/12 ml-16 md:ml-0"><Card className="project-card"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-xl text-foreground mb-3">{exp.title}</CardTitle><div className="flex items-center gap-2 text-accent"><Building className="h-4 w-4" /><span className="font-medium">{exp.company}</span></div></div>{"current" in exp && exp.current && <Badge className="bg-accent/15 text-accent border-accent/30">Current</Badge>}</div><div className="space-y-2 mt-4 text-sm text-muted-foreground"><div className="flex items-center gap-2"><MapPin className="h-4 w-4" />{exp.location}</div><div className="flex items-center gap-2"><Calendar className="h-4 w-4" />{exp.period}</div><Badge variant="outline" className="border-border text-muted-foreground">{exp.type}</Badge></div></CardHeader><CardContent><div className="flex items-center gap-2 mb-3"><Briefcase className="h-4 w-4 text-accent" /><h4 className="text-sm font-semibold text-foreground">Responsibilities</h4></div><ul className="space-y-2 text-sm text-muted-foreground list-disc pl-5">{exp.description.map(item => <li key={item}>{item}</li>)}</ul><div className="flex flex-wrap gap-2 mt-5">{exp.technologies.map(tech => <Badge key={tech} variant="secondary">{tech}</Badge>)}</div></CardContent></Card></div></motion.div>)}</div></div></div>
}

export function Experience() {
  return <section id="experience" className="section-padding"><div className="container-custom"><div className="text-center mb-16"><p className="eyebrow">02 / EXPERIENCE</p><h2 className="heading-2 text-foreground mb-4">Professional Experience & University Leadership</h2><p className="text-muted-foreground max-w-3xl mx-auto text-lg">Building production SaaS features and dependable delivery workflows.</p></div><ExperienceGroup title="Professional Experience" intro="Building production SaaS features, backend services, and dependable delivery workflows." items={professionalExperience} /><ExperienceGroup title="University Experience" intro="Supporting students and campus operations through mentorship, onboarding, and clear coordination." items={universityExperience} /></div></section>
}
